#!/usr/bin/env python3
"""Post new articles to Instagram after tweet fetch.

Posts the branded card generated by generate_instagram_cards.py (not the raw
tweet image). Unlike Facebook, the Instagram Graph API only accepts a public
image URL (no direct file upload), so we point it at raw.githubusercontent.com
— the workflow commits and pushes the card before this script runs, so the
URL is already live without waiting for the GitHub Pages build to finish.
"""

import os
import time
from pathlib import Path

import requests

REPO_ROOT = Path(__file__).resolve().parent.parent
POSTS_DIR = REPO_ROOT / "_posts"
STATE_FILE = REPO_ROOT / "scripts" / ".last_instagram_post"
CARDS_DIR = REPO_ROOT / "assets" / "images" / "instagram-cards"
GRAPH_API_VERSION = "v21.0"
RAW_CONTENT_BASE = "https://raw.githubusercontent.com/tsurdan/Milifney-100/main"

HASHTAGS = "#לפני100שנה #היסטוריה #חדשות #מהעיתונות"

IG_USER_ID = os.environ.get("INSTAGRAM_ACCOUNT_ID", "")
ACCESS_TOKEN = os.environ.get("FACEBOOK_PAGE_ACCESS_TOKEN", "")


def get_last_posted_timestamp():
    """Get the filename of the last post sent to Instagram."""
    if STATE_FILE.exists():
        return STATE_FILE.read_text().strip()
    return ""


def save_last_posted_timestamp(filename):
    STATE_FILE.write_text(filename)


def parse_post(filepath):
    """Extract title, tweet_id, and excerpt from a post file."""
    content = filepath.read_text(encoding="utf-8")
    lines = content.split("\n")

    meta = {}
    in_front = False
    body_start = 0
    for i, line in enumerate(lines):
        if line.strip() == "---":
            if not in_front:
                in_front = True
            else:
                body_start = i + 1
                break
        elif in_front:
            if ":" in line:
                key, val = line.split(":", 1)
                meta[key.strip()] = val.strip().strip('"').strip("'")

    body_lines = lines[body_start:]
    body_text = " ".join(l.strip() for l in body_lines if l.strip() and not l.startswith("!["))

    return {
        "title": meta.get("title", ""),
        "tweet_id": meta.get("tweet_id", ""),
        "body": body_text,
    }


def format_caption(post_data):
    """Format the Instagram caption (no clickable links — IG doesn't linkify captions)."""
    title = post_data["title"]
    body = post_data["body"]
    return f"{title}\n\n{body}\n\n{HASHTAGS}"


def post_to_instagram(image_url, caption):
    """Create a media container, then publish it. Returns True on success."""
    api_base = f"https://graph.facebook.com/{GRAPH_API_VERSION}/{IG_USER_ID}"

    resp = requests.post(f"{api_base}/media", data={
        "image_url": image_url,
        "caption": caption,
        "access_token": ACCESS_TOKEN,
    }, timeout=30)
    if resp.status_code != 200:
        print(f"  [ERROR] Container creation failed: {resp.status_code} - {resp.text}")
        return False
    creation_id = resp.json().get("id")

    # Container processing is usually near-instant for a single image, but
    # give it a moment before publishing to avoid a premature "not ready" error.
    time.sleep(5)

    resp = requests.post(f"{api_base}/media_publish", data={
        "creation_id": creation_id,
        "access_token": ACCESS_TOKEN,
    }, timeout=30)
    if resp.status_code == 200:
        return True
    else:
        print(f"  [ERROR] Publish failed: {resp.status_code} - {resp.text}")
        return False


def main():
    print("=== Instagram poster ===")

    if not IG_USER_ID or not ACCESS_TOKEN:
        print("No INSTAGRAM_ACCOUNT_ID or FACEBOOK_PAGE_ACCESS_TOKEN configured. Skipping.")
        return

    last_filename = get_last_posted_timestamp()
    print(f"Last posted file: {last_filename or '(none)'}")

    all_posts = sorted(POSTS_DIR.glob("*.md"))
    if not all_posts:
        print("No posts found.")
        return

    if last_filename:
        new_posts = [p for p in all_posts if p.name > last_filename]
    else:
        # First run: only post the latest one (don't spam 800+ posts)
        new_posts = all_posts[-1:]

    if not new_posts:
        print("No new posts to send.")
        return

    print(f"Found {len(new_posts)} new post(s) to send.")

    for filepath in new_posts:
        post_data = parse_post(filepath)
        tweet_id = post_data.get("tweet_id", "")
        card_path = CARDS_DIR / f"{tweet_id}.jpg"
        if not tweet_id or not card_path.exists():
            print(f"  [SKIP] No generated card for: {post_data['title']}")
            save_last_posted_timestamp(filepath.name)
            continue

        print(f"  Sending: {post_data['title']}")
        image_url = f"{RAW_CONTENT_BASE}/assets/images/instagram-cards/{tweet_id}.jpg"
        caption = format_caption(post_data)

        success = post_to_instagram(image_url, caption)
        if success:
            print(f"  ✓ Sent!")
            save_last_posted_timestamp(filepath.name)
        else:
            print(f"  ✗ Failed, stopping.")
            break


if __name__ == "__main__":
    main()

